### PR TITLE
Upgrade to latest npm-registry-client to resolve #4

### LINKED ISSUE #4: Update npm-registry-client dependency
Looks like older versions of [**npm-registry-client**](https://www.npmjs.com/package/npm-registry-client) may include potentially risky versions of [**semver**](https://www.npmjs.com/package/semver) (see [advisory](https://nodesecurity.io/advisories/semver_redos)).

Upgrading to the latest **npm-registry-client** should bump to latest, patched **semver** module and avoid any errors people may see if they use a tool like [**nsp**](https://www.npmjs.com/package/nsp) to watch their packages/shrinkwrap.

### PR DESCRIPTION
**Pull request by chetanddesai**
This install pulled `semver@4.3.3` for me which will resolve the [nsp](https://nodesecurity.io) reported [semver vulnerability](https://nodesecurity.io/advisories/semver_redos)

### CODE REVIEW

**Comment by coreycaverly** [comment]
+1

**Comment by turboki** [comment]
+1

**Comment by juliangruber** [comment]
cheers! published as 1.0.0

**Comment by chetanddesai** [comment]
Thanks @juliangruber!

**Pull request merged**
